#!/bin/bash

echo "🚀 13F Scraper Deployment Guide"
echo "=================================="
echo ""
echo "Choose your deployment platform:"
echo "1. Railway (Recommended - Free & Easy)"
echo "2. Heroku (Free tier available)"
echo "3. Render (Free tier available)"
echo "4. Local Network (Share with your team)"
echo ""
echo "Option 1: Railway Deployment"
echo "----------------------------"
echo "1. Go to https://railway.app"
echo "2. Sign up with GitHub"
echo "3. Click 'New Project' → 'Deploy from GitHub repo'"
echo "4. Select your aiprojects repository"
echo "5. Set branch to '13f-scraper'"
echo "6. Railway will automatically detect Python and deploy"
echo "7. Add environment variable: SEC_USER_AGENT='Your Name (email@domain.com) - Your Firm'"
echo "8. Your app will be live at: https://your-app-name.railway.app"
echo ""
echo "Option 2: Heroku Deployment"
echo "---------------------------"
echo "1. Install Heroku CLI: https://devcenter.heroku.com/articles/heroku-cli"
echo "2. Run: heroku login"
echo "3. Run: heroku create your-app-name"
echo "4. Run: git push heroku 13f-scraper:main"
echo "5. Set environment variable: heroku config:set SEC_USER_AGENT='Your Name (email@domain.com) - Your Firm'"
echo "6. Your app will be live at: https://your-app-name.herokuapp.com"
echo ""
echo "Option 3: Local Network (Immediate Solution)"
echo "--------------------------------------------"
echo "1. Run: python3 start_frontend.py"
echo "2. Find your local IP: ifconfig | grep 'inet ' | grep -v 127.0.0.1"
echo "3. Share the IP with your team: http://YOUR_IP:8000"
echo "4. They can access it from anywhere on your network"
echo ""
echo "Option 4: Render Deployment"
echo "---------------------------"
echo "1. Go to https://render.com"
echo "2. Sign up with GitHub"
echo "3. Click 'New' → 'Web Service'"
echo "4. Connect your aiprojects repository"
echo "5. Set branch to '13f-scraper'"
echo "6. Build Command: pip install -r requirements.txt"
echo "7. Start Command: python3 start_frontend.py"
echo "8. Add environment variable: SEC_USER_AGENT"
echo ""
echo "🎯 Quick Start for Railway (Recommended):"
echo "1. Visit: https://railway.app"
echo "2. Connect GitHub → Select aiprojects → 13f-scraper branch"
echo "3. Deploy → Add SEC_USER_AGENT → Done!"
echo ""
echo "Your app will be live in minutes with a real URL you can share!"
